# Generated by Django 4.2.4 on 2023-08-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Crypto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Crypto name")),
                (
                    "abbreviation",
                    models.CharField(
                        max_length=20, verbose_name="Crypto name abbreviation"
                    ),
                ),
                (
                    "purchase_price",
                    models.BigIntegerField(verbose_name="Crypto purchase price"),
                ),
                (
                    "sale_price",
                    models.BigIntegerField(verbose_name="Crypto sales price"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Crypto logo"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="date joined"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="update date"),
                ),
            ],
        ),
    ]
